import { Inter, DM_Sans, Epilogue } from "next/font/google";
import localFont from "next/font/local";
import "react-big-calendar/lib/css/react-big-calendar.css";
import "../styles/globals.css";
import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";
import Body from "~/components/shared/body";
import AuthProvider from "~/components/shared/providers/auth_provider";
import GlobalsGetter from "~/components/shared/getters/globals_getter";
import { Toaster } from "~/components/landing/ui/toaster";

const epilogue = Epilogue({ subsets: ["latin"], variable: "--epilogue" });
const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--dm_sans" });
const din_condensed = localFont({
   src: "../../public/fonts/D-DINCondensed.otf",
   variable: "--din_condensed",
});

const din_alternate = localFont({
   src: "../../public/fonts/DINAlternate-Bold.ttf",
   variable: "--din_alternate",
});

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es">
         <head>
            <link rel="icon" href="/favicon.ico" sizes="any" />
         </head>
         <Body
            className={cn(
               epilogue.variable,
               inter.variable,
               dm_sans.variable,
               din_condensed.variable,
               din_alternate.variable,
               "font-inter",
            )}
         >
            <TRPCReactProvider>
               <GlobalsGetter />
               <AuthProvider>{children}</AuthProvider>
            </TRPCReactProvider>
            <Toaster />
         </Body>
      </html>
   );
}
